version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
